version: '3.5'
services:
  api:
    build: .
    restart: always
    ports:
      - "8082:8082"
    volumes:
      - .:/usr/src/app
    environment:
      - ENV=development
      - PORT=8082
      - DB=mongodb://mongodb:27017/car_park_db
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: "car_park_db_container"
    environment:
      - MONGO_DATA_DIR=/usr/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_ROOT_HOST=%
    volumes:
      - ./data/db:/usr/data/db
    ports:
      - "27017:27017"
    restart: always